/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./components/shared/BaseIcon.vue')['default']
    BaseImage: typeof import('./components/shared/BaseImage.vue')['default']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RadioWithThumbnail: typeof import('./components/feature/RadioWithThumbnail.vue')['default']
    TabDashboard: typeof import('./components/feature/TabDashboard.vue')['default']
    TabDetails: typeof import('./components/feature/TabDetails.vue')['default']
    TabDetailsBody: typeof import('./components/feature/TabDetailsBody.vue')['default']
    TabDetailsSideNavigator: typeof import('./components/feature/TabDetailsSideNavigator.vue')['default']
    TabSettings: typeof import('./components/feature/TabSettings.vue')['default']
    ViewSideBySide: typeof import('./components/feature/ViewSideBySide.vue')['default']
  }
}
