/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: (typeof import('./components/shared/BaseIcon.vue'))['default']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    TabDashboard: (typeof import('./components/feature/TabDashboard.vue'))['default']
    TabDetails: (typeof import('./components/feature/TabDetails.vue'))['default']
    TabDetailsBody: (typeof import('./components/feature/TabDetailsBody.vue'))['default']
    TabDetailsSideNavigator: (typeof import('./components/feature/TabDetailsSideNavigator.vue'))['default']
    TabSettings: (typeof import('./components/feature/TabSettings.vue'))['default']
  }
}
